" ==========================================
" Title: my .vimrc
"
" Author: john-sth
"
" Description: 
"
" Usage: 
" ==========================================


" ===============================
" KEYBINDINGS
" ===============================

let mapleader =" "
"map <leader>x :execute 'silent! !bash ~/.local/bin/vim_to_tmux.sh' <Bar> redraw!<CR>
nnoremap <leader>x :stop<CR>:execute 'silent! !bash ~/.local/bin/vim_to_tmux.sh'<CR>
map <leader>c :w !xclip -selection clipboard<CR>
" Remap Escape Mode Keys
imap jj <Esc>
" open new file in current vim session
nnoremap <Leader>F :tabnew \| Files ~/<CR>
nnoremap <Leader>e :tabnew \| Files $PWD<CR>

inoremap jh <Bar>
inoremap jt ~
inoremap jr {
inoremap je }
inoremap jb [
inoremap jc ]

" vv to generate new vertical split
"map <leader>v :vsplit<CR>:Files ~/ <CR>
nnoremap <leader>v :vsplit<CR>:wincmd l<CR>:enew<CR>:Files ~/<CR>
nnoremap <leader>h :belowright split<CR>:wincmd l<CR>:enew<CR>:Files ~/<CR>
map <leader>w <C-w>

"spawn terminal in current vim session
"map <leader>t :bo term <CR>
map <leader>t :let $VIM_DIR=expand('%:p:h')<CR>:bo term<CR>cd $VIM_DIR<CR>clear<CR>

set pastetoggle=<f5>

"nerd tree
map <leader>n :NERDTreeToggle<CR>

nnoremap \ :Rg<CR>
nnoremap <C-T> :Files<cr>
nnoremap <Leader>b :Buffers<cr>
nnoremap <Leader>s :BLines<cr>


" Edit vimrc configuration file
nnoremap <Leader>ve :e $MYVIMRC<CR>
" " Reload vimrc configuration file
nnoremap <Leader>vr :source $MYVIMRC<CR>

function! StartTmux()
    execute '!tmux attach-session -t your_session_name || tmux new-session -s your_session_name'
endfunction

command! Tmux call StartTmux()

" Turn off highlight search
nmap <silent> ,/ :nohlsearch<CR>

" ===================================================
" BEHAVIOR
" ===================================================

" New lines inherit the indentation of previous lines 
:set autoindent       " Copies the indent from the previous line
:set smartindent      " Adds extra indentation in some cases
:set shiftwidth=4     " Sets the number of spaces for each indent level
" Set tab width to 2 columns.
:set tabstop=4        " Sets the number of spaces for a tab
"on pressing tab, insert 4 spaces
:set expandtab        " Converts tabs to spaces

filetype plugin indent on

" autoindent for files
set ai
set si
            
" set bigger history of executed commands 
set history=1000

" show current mode at the bottom 
set showmode

" show partial typed commands in status line  
set showcmd

set showmatch
set matchtime=3

" autocomplete features for tab and other 
set completeopt=menu,menuone,noselect
set wildmenu

"support for nasm autocompletion
autocmd BufReadPost *.asm setf nasm

" set zathura pdf viewer as default for latex files
let g:vimtex_view_method = 'zathura'

" Use highlighting when doing a search.
set hlsearch

" Ignore capital letters during search.
set ignorecase

" While searching though a file incrementally highlight matching characters as you type.
set incsearch

"disable continuing comments at new line
set formatoptions-=cro

" Add numbers to each line on the left-hand side.
set number
" turn relative numbers on 
set relativenumber
" Highlight cursor line underneath the cursor horizontally.
set cursorline

" Set the window’s title, reflecting the file currently being edited
set title

" disable beep on errors 
set noerrorbells

" display command line's tab complete options as a menu
set wildmenu

" Load an indent file for the detected file type.
filetype indent on

" Enable plugins and load plugin for the detected file type.
filetype plugin on

" Enable type file detection. Vim will be able to try to detect the type of
" file in use
filetype on


" ===================================================
"Terminal
" ===================================================
set termwinsize=10x200
highlight TabLineFill ctermfg=LightGreen ctermbg=DarkGreen
highlight TabLine ctermfg=Blue ctermbg=Yellow
highlight TabLineSel ctermfg=Red ctermbg=Yellow


" ===================================================
" PLUGINS
" ===================================================

call plug#begin('~/.config/vim/plugged')
"plugin providing linting (syntax checking and semantic errors)
Plug 'dense-analysis/ale'
" post install (yarn install | npm install) then load plugin only for editing supported files
Plug 'prettier/vim-prettier', { 'do': 'yarn install --frozen-lockfile --production' }
" nerdtree provides  a file manager feature in vim
Plug 'preservim/nerdtree'
Plug 'ayu-theme/ayu-vim'
Plug 'vim-airline/vim-airline'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'junegunn/rainbow_parentheses.vim'
Plug 'morhetz/gruvbox'
Plug 'junegunn/goyo.vim'
Plug 'tibabit/vim-templates'
Plug 'ycm-core/YouCompleteMe'
Plug 'jremmen/vim-ripgrep'
" rust support
Plug 'rust-lang/rust.vim'
call plug#end()

set grepprg=rg\ --vimgrep\ --smart-case\ --hidden\ --follow
let g:rg_derive_root='true'


" ===================================================
" STYLE
" ===================================================
" Always display the status bar 
set laststatus=2 
set statusline=%F%m%r%h%w%=(%{&ff}/%Y)\ (line\ %l\/%L,\ col\ %c)\

" always show cursor position
set ruler

" Colors for vim 
"...
"set termguicolors     " enable true colors support
"let ayucolor="light"  " for light version of theme
"let ayucolor="mirage" " for mirage version of theme
""let ayucolor="dark"   " for dark version of theme
colorscheme gruvbox
set background=dark    " Setting dark mode
"colorscheme ayu

" Turn syntax highlighting on.
syntax on
set clipboard=unnamedplus

set guifont=DejaVu\ Sans\ Mono:h13
"let g:airline_theme = "afterglow"

"pathogen.vim 
execute pathogen#infect()


" ===================================================
" Text rendering Options
" ===================================================

" Wrap lines at convenient points, avoid wrapping a line in the middle of a word
set linebreak

" Open new file in a new Window
let g:netrw_browse_split = 4



" ===================================================
" Swap and backup file options
" ===================================================
" place where vim will store all swap files 
"set directory=$HOME/.config/vim/vim/swp/


" ==========================================
" MISC
" ==========================================
" press F2 before pasting code in vim, preserves indentation
set pastetoggle=<F2>
" Disable compatibility with vi which can cause unexpected issues.
set nocompatible
" ==========================================

" run this in case the error "no python3 provider found" appears 
" python3 -m pip install --user --upgrade pynvim
" if  "externally-managed-environment" Error appears : 
" cd /usr/lib/python3.11
"sudo rm EXTERNALLY-MANAGED

" if the ycmd server shut down error occures : 
" cd ~/.vim/plugged/youcompleteme
" python3 install.py
" optional : install cmake package 
" =========================================
" disable vim help menu 
:nmap <F1> :echo<CR>
:imap <F1> <C-o>:echo<CR>

" Check spelling in English
set spell
